### PR TITLE
Fixing AddServiceDetails page rendering issues

### LINKED ISSUE #55: Dropdown in Add Service details page is broken
Screenshot 2019-09-14 at 3 29 39 PM

### PR DESCRIPTION
**Pull request by ivinjose**
Fixes #55 #54 #53

### CODE REVIEW

File: src/components/AddServiceDetails/AddServiceDetails.js [hunk 1]
```diff
@@ -51,22 +51,28 @@ class AddServiceDetails extends React.Component {
...
-									<MenuItem key={vehicle._id} value={vehicle.name} primaryText={vehicle.name} />
-								)
-							})
-
-						}
-						</SelectField>
+						<FormControl className={styles['form-control']}>
+							<InputLabel htmlFor="age-helper">Choose your vehicle</InputLabel>
+							<Select 
+								fullWidth={true}
```
Comment (cijokb) [inline src/components/AddServiceDetails/AddServiceDetails.js]: Remove fullWidth props, It is not part of Select, it's part of SelectField

File: src/components/AddServiceDetails/AddServiceDetails.js [hunk 2]
```diff
@@ -51,22 +51,28 @@ class AddServiceDetails extends React.Component {
...
-						}
-						</SelectField>
+						<FormControl className={styles['form-control']}>
+							<InputLabel htmlFor="age-helper">Choose your vehicle</InputLabel>
+							<Select 
+								fullWidth={true} 
+								value={this.state.currentVehicle} 
+								onChange={this.updateVehicle.bind(this)}>
+							{
+								this.state.vehicles.map(function(vehicle, index){
```
Comment (cijokb) [inline src/components/AddServiceDetails/AddServiceDetails.js]: Remove index, as it's not used. Also, it will be good to use arrow function
